[appendix]
== Glossary

[glossary]
Authentication(((Authentication)))[[authentication]]:: Validating the identity of an user.
First step in flow to create authorized access.
_Who is the user?_
Authorization(((Authorization)))[[authorization]]:: Checking if the already authenticated user has the privilege to do something.
_What are you allowed to do?_
Authorization Process(((Authorization Process)))[[authorization-process]]:: The process through which the authorization server determines whether it should issue an [[RPT]] to the client on the requesting party's behalf, based on a variety of inputs.
A key component of the process is authorization assessment.
Authorization Server(((Authorization Server)))[[authorization-server]]:: The service handling the user authorization.
Often the same service also handles the authentication - without <<authentication>> no <<authorization>> may take place.. By default an <<OpenID Connect>> service.
Authz code(((OIDC, Authz code)))[[authz-code]]:: The authorization code of the <<OpenID Connect>> flow for user authentication.
Claim(((Claim)))[[claim]]:: A statement of the value or values of one or more attributes of an entity.
The authorization server typically needs to collect and assess one or more claims of the requesting party or client against policy conditions as part of protecting a resource.
The two methods available for UMA claims collection are claims pushing and interactive claims gathering.
Note: Claims collection might involve authentication for unique user identification, but depending on policy conditions might additionally or instead involve the collection of non-uniquely identifying attributes, authorization for some action, or other statements of agreement.
Claim Token(((Claim Token)))(((Claim, Token)))[[claim-token]]:: A package of claims provided directly by the client to the authorization server through claims pushing.
Entity(((Entity)))[[entity]]:: an acting user or system that needs to be authorized.
HTTP(((HTTP)))[[HTTP]]:: Hyper Text Transfer Protocol
IETF(((IETF)))[[IETF]]:: Internet Engineering Task Force, the standardization body of the internet.
Kubernetes (k8s)(((Kubernetes)))(((k8s)))[[k8s]][[kubernetes]]:: A container orchestration software, originally developed by Google.
OCP(((OCP)))[[ocp]]:: OpenShift Container Platform.
The enterprise <<kubernetes>> provided by Red Hat.
OIDC(((OIDC)))[[oidc]]:: Short form for <<OpenID Connect>>.
OpenID Connect(((OIDC)))(((OpenID Connect)))[[openid-connect]]:: An authentication and authorization protocol defined for use with <<HTTP>>.
Permission(((Permission)))[[permission]]:: Authorized access to a particular resource with some number of scopes bound to that resource.
A permission ticket represents some number of requested permissions.
An <<RPT>> represents some number of granted permissions.
Permissions are part of the authorization server's process and are opaque to the client.
Permission Ticket(((Permission Ticket)))[[permission-ticket]]:: A correlation handle representing requested permissions that is created and maintained by the authorization server, initially passed to the client by the resource server, and presented by the client at the token endpoint and during requesting party redirects.
Persisted Claims Token (PCT)(((Persisted Claims Token)))(((Claim Token, Persisted Claims Token)))(((PCT)))[[PCT]][[persistet-claims-token]]:: A correlation handle issued by an authorization server that represents a set of claims collected during one authorization process, available for a client to use in attempting to optimize a future authorization process.
Resource(((Resource)))[[resource]]:: The data protected by <<UMA>> <<scope>>s.
Resource Owner(((Resource Owner)))[[resource-owner]]:: The owner of a <<Resource>> protected on the <<Resource Server>>.
Resource Server(((Resource Server)))[[resource-server]]:: The service handling the <<Resource>>s.
Requesting Party(((Requesting Party)))[[requesting-party]]:: The <<entity>> trying to access a protected <<resource>>.
Requesting Party Token (RPT)(((Requesting Party Token)))(((RPT)))[[requesting-party-token]][[RPT]]:: An OAuth access token associated with the UMA grant.
An RPT is unique to a requesting party, client, authorization server, resource server, and resource owner.
RSID[[rsid]]:: The Resource ID as issued by the <<Authorization Server>>.
Request for Comment (RFC)(((RFC)))(((IETF, RFC)))[[RFC]]:: Request for Comment, the standardization documents of the IETF
Scope(((Scope)))[[scope]]:: IN <<UMA>> the scope defines the privileges of an <<entity>>.
UMA(((UMA)))[[UMA]]:: User Managed Authorization
