[appendix]
== Glossary
[glossary]

Authentication(((Authentication)))[[authentication]]:: Validating the identity of an user. First step in flow to create authorized access. _Who is the user?_
Authorization(((Authorization)))[[authorization]]:: Checking if the already authenticated user has the privilege to do something. _What are you allowed to
do?_
Authorization Server(((Authorization Server)))[[authorization-server]]:: The service handling the user authorization. Often the same service also handles the
authentication - without <<authentication>> no <<authorization>> may take place.. By default an <<OpenID Connect>> service.
Authz code(((OIDC, Authz code)))[[authz-code]]:: The authorization code of the <<OpenID Connect>> flow for user authentication.
Entity(((Entity)))[[entity]]:: an acting user or system that needs to be authorized.
HTTP(((HTTP)))[[http]]:: Hyper Text Transfer Protocol
IETF(((IETF)))[[ietf]]:: Internet Engineering Task Force, the standardization body of the internet.
Kubernetes(((Kubernetes)))[[kubernetes]]:: A container orchestration software, originally developed by Google.
OCP(((OCP)))[[ocp]]:: OpenShift Container Platform. The enterprise <<kubernetes>> provided by Red Hat.
OIDC(((OIDC)))[[oidc]]:: Short form for <<OpenID Connect>>.
OpenID Connect(((OIDC)))(((OpenID Connect)))[[openid-connect]]:: An authentication and authorization protocol defined for use with <<HTTP>>.
PRT(((UMA flow, PRT)))[[prt]]::
Resource(((Resource)))(((UMA flow, resource)))[[resource]]:: The data protected by <<UMA>> <<scope>>s.
Resource Owner(((Resource Owner)))(((UMA flow, resource owner)))[[resource-owner]]:: The owner of a <<Resource>> protected on the <<Resource Server>>.
Resource Server(((Resource Server)))(((UMA flow, resource server)))[[resource-server]]:: The service handling the <<Resource>>s.
Requesting Party(((Requesting Party)))(((UMA flow, requesting party)))[[requesting-party]]:: The <<entity>> trying to access a protected <<resource>>.
RSID(((UMA flow, RSID)))[[rsid]]:: The Resource ID as issued by the <<Authorization Server>>.
RFC(((RFC)))(((IETF, RFC)))[[rfc]]:: Request for Comment, the standardization documents of the IETF
Scope(((Scope)))(((UMA flow, Scope)))[[scope]]:: IN <<UMA>> the scope defines the privileges of an <<entity>>.
UMA(((UMA flow)))[[uma]]:: User Managed Authorization
