[appendix]
== Glossary
[glossary]

Authentication:: Validating the identity of an user. First stepp in flow to create authorized access. _Who is the user?_
Authorization:: Checking if the already authenticated user has the privilege to do something. _What are you allowed to
do?_
Authorization Server:: The service handling the user authorization. Often the same service also handles the
authentication - without <<authentication>> no <<authorization>> may take place.. By default an <<OpenID Connect>> service.
Authz code:: The authorization code of the <<OpenID Connect>> flow for user authentication.
Entity:: an acting user or system that needs to be authorized.
HTTP:: Hyper Text Transfer Protocol
IETF:: Internet Engineering Task Force, the standardization body of the internet.
Kubernetes:: A container orchestration software, originally developed by Google.
OCP:: OpenShift Container Platform. The enterprise <<kubernetes>> provided by Red Hat.
OIDC:: Short form for <<OpenID Connect>>.
OpenID Connect:: An authentication and authorization protocol defined for use with <<HTTP>>.
PRT::
Resource:: The data protected by <<UMA>> <<scope>>s.
Resource Owner:: The owner of a <<Resource>> protected on the <<Resource Server>>.
Resource Server:: The service handling the <<Resource>>s.
RSID:: The Resource ID as issued by the <<Authorization Server>>.
RFC:: Request for Comment, the standardization documents of the IETF
Scope:: IN <<UMA>> the scope defineds the privileges of an <<entity>>.
UMA:: User Managed Authorization
